### ISSUE TITLE
Composite key index fail for YAML

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#15807]
See https://github.com/hazelcast/hazelcast/issues/15806, if YAML incorrect no warning, this issue is if YAML correct still nothing happens.

This, on 3.12.3, doesn't result in an index:

```
      indexes:
      - type: HASH
        attributes:
          - "__key#hello"
```
