### ISSUE TITLE
Silent YAML failure for composite key index

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#15806]
If an index is defined in XML as
```
<index ordered="false">__key.hello</index>
```
the message 
```
com.hazelcast.config.MapIndexConfig      : __key used without a following '#' char in index attribute '__key.hello'. Don't you want to index a key?
```

If the same is attempted in YAML as
```
      indexes:
      - type: HASH
        attributes:
          - "__key.hello"
```
no warning appears.

A silent fail.

Validated on 3.12.3
