### ISSUE TITLE
Allow "empty" wan-replication-ref in YAML config

### ISSUE THREAD

**Issue by blazember** [hazelcast/hazelcast#16671]
In 4.0 `merge-policy-class-name` under `wan-replication-ref` config made optional by introducing a default. With this change, "empty" `wan-replication-ref` is possible with setting only the name of it. In XML it looks like the following.
```
<map name="wan-replicated-map">
    <wan-replication-ref name="wan-sample"/>
</map>
```
But in YAML the same configuration is not straightforward:
```
map:
  wan-replicated-map:
    wan-replication-ref:
      wan-sample: {}
```
Instead - since `map:wan-replication-ref` is a 1:* mapping, the YAML config structure should look like this:
```
map:
  wan-replicated-map:
    wan-replication-ref:
      name: wan-sample
```

When implementing this change, the support for the old-style `wan-replication-ref` configuration should be kept for backward-compatibility reasons backed with tests. The documentation and the examples should present the new way. After implemented the `merge-policy-class-name` should be removed from `basic-sample` WAN sample in the code samples repo.
