### ISSUE TITLE
YAML handling of Discovery Strategy

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#16792]
In 4.0, the following is required to set a discovery strategy

```
          discovery-strategies:
            discovery-strategies:
              - class: neil.demo.MyDiscoveryStrategy
                enabled: true
 ```

based on https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/resources/hazelcast-full-example.yaml#L658 and this works.

The inner section https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/resources/hazelcast-full-example.yaml#L661 should be `discovery-strategy` not `discovery-strategies`

Also, it does not seem possible to configure a DiscoveryStrategyFactory, a DiscoveryServiceFactory or a DiscoveryService from YAML
