### ISSUE TITLE
how can I escape ser/des?

### ISSUE THREAD

**Issue by samekim** [hazelcast/hazelcast#17986]
**Describe the bug**
```
  map:
    COMMUNITY:
      in-memory-format: BINARY
      cache-deserialized-values: ALWAYS
      statistics-enabled: true
      max-idle-seconds: 21600
      eviction:
        comparator-class-name: xxxx
        max-size-policy: PER_NODE
        size: 100
      map-store:
        enabled: true
        initial-mode: LAZY
        class-name: xxxxx
        write-coalescing: true
      near-cache:
        time-to-live-seconds: 0
        max-idle-seconds: 3600
        invalidate-on-change: true
        in-memory-format: OBJECT
        cache-local-entries: true
        eviction:
          size: 100
          max-size-policy: ENTRY_COUNT
          eviction-policy: LFU
```
I've turned on 'cache-deserialized-values', 'near-cache.in-memory-format: Object' and 'cache-local-entries: true'.
but It does not stop serializations/deserializations.
and some nodes does not hit the near cache.

```
* Node A
20-12-2020 01:51:59 1608396719241 Metric[[name=COMMUNITY,unit=count,metric=map.hits]=561]
20-12-2020 01:51:59 1608396719241 Metric[[name=COMMUNITY,unit=count,metric=map.nearcache.hits]=2231]

* Node B
20-12-2020 01:52:01 1608396721810 Metric[[name=COMMUNITY,unit=count,metric=map.hits]=2372]
20-12-2020 01:52:01 1608396721810 Metric[[name=COMMUNITY,unit=count,metric=map.nearcache.hits]=584]
```

**Expected behavior**
how to hit the local near cache and escape ser/des?
