### ISSUE TITLE
Hazelcast client doesn't receive membership events when hot restart persistence is enabled

### ISSUE THREAD

**Issue by emre-aydin** [hazelcast/hazelcast#18234]
**Describe the bug**
Hazelcast Java client doesn't receive `MembershipEvent`s in its `MembershipListener` when a member is restarted if the member has hot restart persistence enabled.

**Expected behavior**
It receives the events when hot restart persistence is disabled. I would expect to get those same events when hot restart is enabled.

**To Reproduce**

1. Start a Hazelcast member v4.1.1 with hot restart persistence enabled
2. Start a Hazelcast client (v4.1.1) that is configured to have a `MembershipListener` configured for it which prints the event when it receives one
3. Stop the member
4. Start the member again
5. Observe that there's no membership event received via the client (whereas in the same scenario, if hot restart is disabled, client does receive the event)

**Additional context**

This difference in behavior for the client cause Management Center to miss when a member leaves/joins a cluster. Management Center relies on these events in more than one places but the most severely affected one is the metrics collection. Since Management Center can't detect the member becoming offline and then becoming online again, it queries for the metrics with a wrong sequence number (sequence number starts from zero when a member is started/restarted, irrespective of the hot restart persistence configuration).

Member has the following configration, client has no configuration other than the `MembershipListener`.

```yaml
hazelcast:
  license-key: ...
  hot-restart-persistence:
    enabled: true
    base-dir: /Users/emre/hot-backup
    backup-dir: /Users/emre/hot-backup
    validation-timeout-seconds: 120
    data-load-timeout-seconds: 900
    cluster-data-recovery-policy: FULL_RECOVERY_ONLY
  map:
    test-map:
      hot-restart:
        enabled: true
        fsync: false
  cache:
    test-cache:
      hot-restart:
        enabled: true
        fsync: false

```
