### ISSUE TITLE
Hazelcast Cache not deleted in k8s near cache

### ISSUE THREAD

**Issue by dino-lee** [hazelcast/hazelcast#18887]
Hello :)
Hazelcast Issue in k8s 
This is my gradle implements
```gradle
 implementation group: 'com.hazelcast', name: 'spring-data-hazelcast', version: '2.4.0'
 implementation group: 'com.hazelcast', name: 'hazelcast-all', version: '4.2'
```

First, Upload all data from MongoDB to the spring data hazelcast repository at Pod Initialize time.
Once Cache Uploaded, data cannot be deleted.
It remains even after deploy restart.
It is used within k8s and uses the Near Cache kubernetes config.

If the Hazelcast Cache method is kubernetes embedded, does the storage exist other than Pod? 
We found that Cache remained even though Pod was all deploy restart.

This is our yaml
svc.yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: test
    app.kubernetes.io/managed-by: kubectl
  name: hazelcast-service
spec:
  selector:
    app: test-app
  ports:
    - name: hazelcast
      port: 5701
  type: ClusterIP
```

deploy yaml
```yaml
          name: test-app
          ports:
            - name: http
              containerPort: 8080
            - name: multicast
              containerPort: 5701

```

Could you tell me the cause of this issue?

Thanks :)
