### ISSUE TITLE
Missing field in addScheduledExecutorConfig protocol definition

### ISSUE THREAD

**Issue by cagric0** [hazelcast/hazelcast#21845]
**CapacityPolicy** field is missing in addScheduledExecutorConfig protocol definition
(https://github.com/hazelcast/hazelcast-client-protocol/blob/master/protocol-definitions/DynamicConfig.yaml#L550-L610) 

The following configuration is taken from [hazelcast-full-example.yaml](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/resources/hazelcast-full-example.yaml#L881-L890)

Except **capacity-policy**, all other fields are available in the protocol definition.

```
scheduled-executor-service:
    default:
      pool-size: 16
      durability: 1
      capacity: 100
      capacity-policy: PER_NODE
      split-brain-protection-ref: splitBrainProtectionRuleWithThreeNodes
      merge-policy:
        batch-size: 100
        class-name: PutIfAbsentMergePolicy
```
