### ISSUE TITLE
Cannot submit job with name 'ClickstreamHandler' before the master node initializes job coordination service's state

### ISSUE THREAD

**Issue by neilstevenson** [hazelcast/hazelcast#22578]
**Describe the bug**
On a one node cluster, this error appears repeatedly when submitting a job

**Expected behavior**
No exception, job starts

**To Reproduce**
Not entirely clear what causes this yet, I have a demo that shows it, but it's hardly minimal

**Additional context**
May be related https://github.com/hazelcast/hazelcast/pull/19530

Tested with 5.2.0-SNAPSHOT

Java is
```
openjdk 17 2021-09-14
OpenJDK Runtime Environment (build 17+35-2724)
OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)
```

Dockerfile is 
```
FROM --platform=linux/amd64 library/python:3.7-buster

# Add Java
RUN apt update
RUN cd /tmp ; \
    wget -q https://download.java.net/java/GA/jdk17/0d483333a00540d886896bac774ff48b/35/GPL/openjdk-17_linux-x64_bin.tar.gz ; \
    tar xf openjdk-17_linux-x64_bin.tar.gz ; 
RUN update-alternatives --install /usr/bin/java java /tmp/jdk-17/bin/java 1
```
and job is launched by the one server once it has started.

**Comment by neilstevenson** [comment]
Same build as https://github.com/hazelcast/hazelcast/issues/22577, a fractionally modified verison of 5.2.0-SNAPSHOT pulled on 2022-10-21.

**Comment by neilstevenson** [comment]
Not conclusive, but this may be caused by https://github.com/hazelcast/hazelcast/issues/22577

When I add `hazelcast.persistence.auto.cluster.state==false` to my config this issue no longer appears. Only had time for one test so far, not conclusive!

**Comment by neilstevenson** [comment]
Reproducer for 5.2.0, run on Kubernetes obviously, with a license key:

```
    public static void main(String[] args) throws InterruptedException {
        Config config = new Config();
        
        //XXX config.getProperties().put("hazelcast.persistence.auto.cluster.state", "false");
        
        config.getNetworkConfig().getJoin().getAutoDetectionConfig().setEnabled(false);
        config.getNetworkConfig().getJoin().getMulticastConfig().setEnabled(false);
        config.getNetworkConfig().getJoin().getKubernetesConfig().setEnabled(true).setProperty("service-dns", "dev.default.svc.cluster.local");

        config.getJetConfig().setEnabled(true);

        config.getPersistenceConfig().setEnabled(true).setBaseDir(new File("/tmp"));

        HazelcastInstance hazelcastInstance = Hazelcast.newHazelcastInstance(config);
        
        Pipeline pipeline = Pipeline.create()
        		.readFrom(TestSources.items("22578"))
        		.writeTo(Sinks.logger())
        		.getPipeline();

        JobConfig jobConfig = new JobConfig();
        jobConfig.setName("job22578");
        
        TimeUnit.SECONDS.sleep(5L);
        System.out.println("Launching " + jobConfig.getName());

        Job job = hazelcastInstance.getJet().newJob(pipeline, jobConfig);

        System.out.println("Launched " + jobConfig.getName() + "," + job.getStatus() + "," + job);
        TimeUnit.HOURS.sleep(1L);
        
        hazelcastInstance.shutdown();
    }
```

with
```
---
apiVersion: v1
kind: Service
metadata:
  name: dev
spec:
  clusterIP: None
  selector:
    app: dev
  ports:
  - port: 5701
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dev
spec:
  replicas: 1
  serviceName: dev
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
        - image: "goes here"
          imagePullPolicy: Always
          name: dev-container
---
```
