### ISSUE TITLE
There is no instances command in hazelcast-cli help

### ISSUE THREAD

**Issue by nkonev** [hazelcast/hazelcast#25548]
What I did

```yaml
version: '3.7'

services:
  hazelcast:
    image: hazelcast/hazelcast:5.3.2
    hostname: hazelcast
    container_name: hazelcast
    restart: unless-stopped
    environment:
      # disables auto join to other nodes
      # https://docs.hazelcast.com/hazelcast/5.3/configuration/configuring-declaratively
      # https://github.com/hazelcast/hazelcast/blob/v5.3.1/hazelcast/src/main/resources/hazelcast-default.yaml
      - HZ_NETWORK_JOIN_AUTODETECTION_ENABLED=false
      - HZ_JET_ENABLED=false
    ports:
      - 5701:5701
      - 5702:5702

```

```
docker-compose up -d
docker exec -it hazelcast bash
hz-cli console
help
```

There is a command instances
![image](https://github.com/hazelcast/hazelcast/assets/3160384/48b84735-6d9e-49aa-b038-a52301e06729)

, but it is missed in the help:
![image](https://github.com/hazelcast/hazelcast/assets/3160384/fbc7c4ef-eaa4-43a8-905a-003a8e669581)
