### ISSUE TITLE
wan-server-socket-endpoint-config broken [HZ-3557]

### ISSUE THREAD

**Issue by javapark1** [hazelcast/hazelcast#25787]
**Describe the bug**
Regardless of setting the port number other than 5701 for **wan-server-socket-endpoint-config**, it always binds to not one but three ports: 5701, 5702, and 5703.

**Expected behavior**
Bind to the configured port. For the example shown below, Member 1 should bind to 6901 and Member 2 should bind to 6902.

**To Reproduce**

1. Configure Hazelcast members with **wan-server-socker-endpoint-config** configured as follows.

```yaml
hazelcast:
...
  advanced-network:
    enabled: true
    join:
      multicast:
        enabled: false
      tcp-ip:
        enabled: true
        members: ${hazelcast-addon.tcp.members}
        interface: 192.168.1.10
    wan-server-socket-endpoint-config:
      port:
        port:  ${hazelcast-addon.wan.tcp.port}
        auto-increment: false
      outbound-ports:
        - 30000-31000
      interfaces:
        enabled: true
        interfaces:
          - 192.*.*.*
```

```bash
# Member 1
java -Dhazelcast-addon.tcp.members=192.168.1.10:6701,192.168.1.10:6702 -Dhazelcast-addon.wan.tcp.port=6901 ...

# Member 2
java -Dhazelcast-addon.tcp.members=192.168.1.10:6701,192.168.1.10:6702 -Dhazelcast-addon.wan.tcp.port=6902 ...
```

2. Start members

**Additional context**
