### ISSUE TITLE
No connection left to client cluster wide

### ISSUE THREAD

**Issue by JesperBerggren** [hazelcast/hazelcast#25934]
**Production cluster fails with "No connection left to client cluster wide"**
In our production cluster we get this error more or less continuously.  
It's a three node Kubernetes cluster with one one Hazelcast member per node. We don't use it extensively and there's plenty of resources  left, both in regards to cpu (8 cpu's limit and 5 gb memory per member).
According to the Management Center everything looks ok and metrics seem fine.
We have around 30 active clients.

**Expected behavior**
I expect the Hazelcast cluster to work without this error. I don't get why more connections aren't just created!?

**To Reproduce**
Unsure.

Unsure. 

**Additional context**
We'er using Istio Service Mesh but it's fully functional and there's no problems with Hazelcast in our lesser environments with less load.

We're using Hazelcast version 5.3.2.
We've installed the Hazelcast cluster via the standard Helm chart (version 5.8.9) with the following values:
```
cluster:
  memberCount: 3

hazelcast:
  yaml:
    hazelcast:
      cluster-name: integration-hazelcast-prod
      instance-name: hzInstance1
      network:
        join:
          auto-detection:
            enabled: false
          multicast:
            enabled: false
          kubernetes:
            enabled: true
            service-dns: hazelcast.integration-tools.svc.cluster.local
            service-name: null
            namespace: null
        rest-api:
          enabled: true
      jet:
        enabled: false
      map:
        default:
          time-to-live-seconds: 600

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - hazelcast
          - key: role
            operator: In
            values:
            - hazelcast
        topologyKey: kubernetes.io/hostname
      weight: 100

resources:
  requests:
    memory: 512Mi
    cpu: 1
  limits:
    memory: 5Gi
    cpu: 8

# The service is not created with the necessary "appProtocol: tcp" in port
# This is necessary for Hazelcast to work with an Istio sidecar
# So instead a manually defined service is created
# Until it has been fixed in either Hazelcast or the helm chart this setup is unfortunately necessary...
service:
  create: false
#  annotations:
#    networking.istio.io/exportTo: "*"

rbac:
  create: false

serviceAccount:
  create: true
  automountToken: true

metrics:
  enabled: true

jet:
  enabled: false

# Hazelcast Management Center application properties
mancenter:
  enabled: true
  devMode:
    enabled: true
  contextPath: hazelcast
  javaOpts: "-Dhazelcast.mc.lock.skip=true"
  yaml:
    hazelcast-client:
      cluster-name: integration-hazelcast-prod
      instance-name: hzInstance1
      network:
        ssl:
          enabled: false
        auto-detection:
          enabled: false
        kubernetes:
          enabled: true
          service-dns: hazelcast.integration-tools.svc.cluster.local
          service-name: null
          namespace: null
  persistence:
    enabled: false
  service:
    type: ClusterIP
    annotations:
      networking.istio.io/exportTo: "istio-system"
```

Please advice.

Best regards
Jesper Berggren
