### ISSUE TITLE
ClassNotFoundException when submitting a Jet pipeline

### ISSUE THREAD

**Issue by maragud** [hazelcast/hazelcast#26343]
**Describe the bug**
I tried submitting a Hazelcast Jet job from a client to the cluster using the following configuration. 
Hazelcast member configuration
```
hazelcast:
  cluster-name: dev
  network:
    join:
      tcp-ip:
        enabled: true
        member-list:
          - <node1>:5701
          - <node2>:5701
          - <node3>:5701
...
  user-code-deployment:
    enabled: false
  jet:
    enabled: true
    resource-upload-enabled: true
```
Hazelcast client configuration
```
hazelcast-client:
  cluster-name: dev
  network:
    cluster-members:
      - <node1>:5701
      - <node2>:5701
      - <node3>:5701
```
Hazelcast client code
```
public static void main(String[] args) {
    Pipeline p = Pipeline.create();
    HazelcastInstance hz = HazelcastClient.newHazelcastClient();
    BatchStage<Long> filter = p.readFrom(TestSources.items(1L, 2L, 3L, 4L))
            .writeTo(Sinks.mapWithUpdating("test", x -> 1L, (BiFunctionEx & Serializable) (x, y) -> x));

    JobConfig jobConfig = new JobConfig()
            .setName("test-pipeline")
            .addPackage("com.example");

    hz.getJet().newJob(p, jobConfig).join();
}
```

While the above example throws a class not found exception if we change the pipeline’s writer to the following it works without throwing an exception. 
```
...
    BatchStage<Long> filter = p.readFrom(TestSources.items(1L, 2L, 3L, 4L))
            .writeTo(Sinks.map("test", x -> 1L, x -> x));
...
```
The `mapWithMerging` method also throws an exception.
Also if the Hazelcast cluster contains only 1 member it will not throw the exception.

After this test, I decided that it is probably better to run the pipeline to the client and use the `remoteMapWith(Updating/Merging)` sink to write the data to the other Hazelcast cluster, but even in this case, I found the same error occurs.

I tried to understand what causes the error, and from what I understood the `com.hazelcast.jet.impl.connector.UpdateMapP.readData` cannot read the `updateFn` in the members because the thread that it is running the `readData` is not using a `JetClassLoader` which contains the classes loaded from the `jobConfig.addPackage("com.example")`, while in the case of the `Sinks.map(...)` it was using the correct class loader.

**Expected behavior**
Run the above example with 2 or more Hazelcast members and a client that submits the job.

**To Reproduce**
As described above

**Additional context**
Hazelcast 5.4.0
Java 17
